services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9500:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  esdata01: