# Generated by Django 5.0.6 on 2024-08-13 09:57

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_post_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.RemoveIndex(
            model_name='post',
            name='tasks_post_search__3e7775_gin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='search_vector',
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['body'], name='body_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
