# Generated by Django 5.0.6 on 2024-08-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_post_options_remove_post_title_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='tasks_post_search__3e7775_gin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='search_vector',
        ),
    ]
