# Generated by Django 5.0.6 on 2024-08-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_list_worked_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='worked_on',
        ),
        migrations.AddField(
            model_name='post',
            name='worked_on',
            field=models.IntegerField(choices=[(0, 'Office'), (1, 'Manufacturer'), (2, 'Customer'), (3, 'Home')], default=0),
        ),
    ]
